version: '3'
services:
  insert_quote:
    image: insert_quote
    container_name: insert_quote
    restart: always
    tty: true
    volumes:
      - '/home/docker/finsuite/fin_suite4.log:/code/fin_suite4.log'
    environment:
      - TZ=Europe/Berlin
    network_mode: host
networks:
  default:
    external:
      name: default_network
