version: '3'
services:
  fmg_stream_fx:
    image: fmg_stream_fx
    container_name: fmg_stream_fx
    restart: always
    tty: true
    volumes:
      - '/home/docker/finsuite/fin_suite4.log:/code/fin_suite4.log'
      - '/home/docker/finsuite/fmg_api.key:/code/fmg_api.key'      
    environment:
      - TZ=Europe/Berlin
    network_mode: host
  fmg_stream_quote:
    image: fmg_stream_quote
    container_name: fmg_stream_quote
    restart: always
    tty: true
    volumes:
      - '/home/docker/finsuite/fin_suite4.log:/code/fin_suite4.log'
      - '/home/docker/finsuite/fmg_api.key:/code/fmg_api.key'      
    environment:
      - TZ=Europe/Berlin
    network_mode: host
networks:
  default:
    external:
      name: default_network