version: '3'
services:
  fmg_analyze_pvs:
    image: fmg_analyze_pvs
    container_name: fmg_analyze_pvs
    restart: always
    tty: true
    volumes:
      - '/home/docker/finsuite/fin_suite4.log:/code/fin_suite4.log'
    environment:
      - TZ=Europe/Berlin
    network_mode: host
networks:
  default:
    external:
      name: default_network
