# set base image (host OS)
FROM python:3.8-slim

# set the working directory in the container
WORKDIR /code

# build a folder for config, logs and output
RUN mkdir ./mylib
COPY ./mylib/* ./mylib/

# copy the dependencies file to the working directory
COPY requirements.txt .

# install dependencies
RUN pip install -r requirements.txt

# copy the content of the local src directory to the working directory
COPY update_company_key_stats.py ./

# command to run on container start
CMD [ "python", "./update_company_key_stats.py" ] 
